### PR TITLE
Mac os build conda

### PR DESCRIPTION
**Pull request by prascle**
MacOS build with Conda libraries, Qt 5.15. Work in progress.
Solves issues #1671, #1553.
The bugs #1830 and #1836 are not yet solved...
A commit is related to the collection of libraries required for the standalone bundle (Python script) and the signature process on macOS.
Several commits deal with some warnings related to Qt 5.15 (deprecated warnings). These commits are not OK for Qt 5.12.

Regards,
Paul

### CODE REVIEW

**Comment by dgirardeau** [comment]
Sorry I switched it to 'ready for review' by mistake. Feel free to change it back to its original state.

And will it be able to compile with Qt < 5.15 with the changes of syntax?

**Comment by prascle** [comment]
The 4 last commits will not work with Qt < 5.15, the previous commit change the GitHub workflow for automatic build with Qt 5.15, The 5 first commits should work with the standard build configuration but I did not get this configuration on my mac to check if it works correctly (the only build configuration I use is the one required for CloudComPy, with Qt 5.15...).
My suggestion is to leave the pull request as draft, but I can't do that myself....

**Comment by dgirardeau** [comment]
I can't turn it back to draft either... ok, no big deal.

In another project, to allow compilation with all versions of Qt, I used a header like this: (included everywhere via precompiled headers, but I guess we could add it to a header included by almost all the others, somewhere in CCCoreLib):

```
#include <QtCore/QString>
#include <QtCore/QTextStream>
#include <QtCore/QtGlobal>

#if QT_VERSION < QT_VERSION_CHECK(5, 14, 0)
// Redefine shortcuts only available since version 5.14
namespace Qt
{
	static auto endl           = ::endl;
	static auto hex            = ::hex;
	static auto SkipEmptyParts = QString::SkipEmptyParts;
	using SplitBehavior        = QString::SplitBehavior;
}
#endif

```

**Comment by prascle** [comment]
Another pull request replace this one.

**Pull request closed without merging**
