### PR TITLE
Move some files from "qCC" into the CCPluginAPI lib

### PR DESCRIPTION
**Pull request by asmaloney**
- {CC source}/ccColorScaleSelector.[h,cpp]
- {CC source}/ccColorScaleEditorDlg.[h,cpp]
- {CC source}/ccColorScaleEditorWidget.[h,cpp]
- {CC source}/ui_templates/colorScaleEditorDlg.ui

...and because it's needed by ccColorScaleEditorDlg: ccPersistentSettings.h

Also changed ccColorScaleEditorDlg from inherited Ui to member variable so we don't need the ui header file exposed.

This is part of #1218

### CODE REVIEW

**Comment by dgirardeau** [comment]
Hum, actually I wanted to create a big library below 'qCC' with all the dialogs, semi-algorithms, etc.

But you can go on with this PR. We'll move the dialog when this big library will be created.

**Comment by asmaloney** [comment]
At the end of the day we may be approaching the same problem from different ends.

What I'm trying to do is separate out the things that plugins can use from the things that are application-specific. In my view, the plugins shouldn't reach into the CC source for anything.

When I'm done this series of PRs (1 more after this I think), the plugins will depend only on the libraries in "libs". (This bundle of libs would effectively be a large-ish plugin SDK...)

What I see is the following:

- CCAppCommon: common code for applications (old "common" - plugins do not use this)
- CCPluginAPI: code that applications & plugins use (added to over time)

I agree that the CloudCompare stuff needs to reorganize (see step in #1218).

I have thoughts on a couple of different ways to reorganize what's currently in qCC - maybe that's best discussed in #1218.

**Comment by dgirardeau** [comment]
Since ccColorScaleSelector will also be used by CC, isn't it a bit weird to have CloudCompare rely on CCPluginAPI?

For me this big 'dialogs' lib will indeed go under 'libs'. And plugins (or any other project) will be of course able to reuse any of them.

**Comment by dgirardeau** [comment]
And I'd like all dialogs to be at the same place if possible (otherwise it's a bit strange for me to have dialogs in various places)

**Comment by asmaloney** [comment]
> Since ccColorScaleSelector will also be used by CC, isn't it a bit weird to have CloudCompare rely on CCPluginAPI?

Maybe the name needs to change. It's more of an SDK that both applications and plugins rely on. That's where dialogs common to CC, ccViewer, and plugins would live.

Any dialogs that are only used by CC actions, for example, would stay in CC. Again - I have ideas on how that might be organized (and I know @WargodHernandez does as well) so that's best discussed in the issue.

**Pull request merged**
