### PR TITLE
Next step to German translation

### PR DESCRIPTION
**Pull request by ryanthara**
New Strings, typos and precision.

### CODE REVIEW

**Comment by dgirardeau** [comment]
Hum, it's strange that your branch has all these commits before 9ba9091... Only the 8 last commits should appear in this PR

**Comment by ryanthara** [comment]
> Hum, it's strange that your branch has all these commits before [9ba9091](https://github.com/CloudCompare/CloudCompare/commit/9ba9091070eb9c56fbfabdef6aaccefd831426b4)... Only the 8 last commits should appear in this PR

Yes. I do not understand this too. During the translation I worked on new_features branch. Before my commit, the branch was gone and I had to merge it into my fork.

**Comment by dgirardeau** [comment]
(In the future, mind that I create these branches only to check that everything compiles fine - thanks to the Continuous Integration mechanism - before merging to master)

**Comment by ryanthara** [comment]
> (In the future, mind that I create these branches only to check that everything compiles fine - thanks to the Continuous Integration mechanism - before merging to master)

OK, then I'll wait until the master is updated.

**Comment by dgirardeau** [comment]
I'm confused. What's new in this PR? (I realize that even the 8 last commits seem to be already on my side when I merged your PR yesterday - see https://github.com/CloudCompare/CloudCompare/pull/1421)

And 'rebasing' is different from 'merging' (here it seems you 'merged' the CloudCompare master branch)

**Comment by ryanthara** [comment]
> I'm confused. What's new in this PR? (I realize that even the 8 last commits seem to be already on my side when I merged your PR yesterday - see #1421)

I finished at least more than 200 new translation Strings from the new_branch.

Bildschirmfoto 2021-03-08 um 23 07 57


> 
> And 'rebasing' is different from 'merging' (here it seems you 'merged' the CloudCompare master branch)

**Comment by dgirardeau** [comment]
Okay, so only https://github.com/ryanthara/CloudCompare/commit/cb8957aa6e2969023f4c7a1ddfcfaa4300d562c2 is new? I'll update your master branch

**Comment by ryanthara** [comment]
> Okay, so only [ryanthara@cb8957a](https://github.com/ryanthara/CloudCompare/commit/cb8957aa6e2969023f4c7a1ddfcfaa4300d562c2) is new?

Yes. I think so. I did not change other files.

>  I'll update your master branch

Thank you.

**Comment by dgirardeau** [comment]
Ok, so your master branch history is quite messed-up (not sure if your tool gives you the choice between rebasing or merging, but when dealing with master branches and remote repos, always prefer 'rebasing').

I've directly cherry-picked your commit on our master branch so as to make things safe (see b55fa745e46d7cc65758129ea99a8b7164d73d07).

I'll reset your master branch next.

**Comment by dgirardeau** [comment]
Ok that's done!

**Comment by dgirardeau** [comment]
Make sure to 'reset' the master branch on your side.

**Pull request closed without merging**
