### PR TITLE
Architecture: Move 3DX mouse support to CCAppCommon

### PR DESCRIPTION
**Pull request by asmaloney**

### CODE REVIEW

**Comment by asmaloney** [comment]
@dgirardeau Since you're the only one who can compile this, can you please confirm that it works?  Thanks.

**Comment by WargodHernandez** [comment]
Actually I can also, I'm about to try it

**Comment by asmaloney** [comment]
Ah cool - thanks!

**Comment by WargodHernandez** [comment]
After clearing cache, I get this when I try to generate cache
```
1> [CMake] CMake Error at libs/CCAppCommon/devices/3dConnexion/CMakeLists.txt:30 (target_link_libraries):
1> [CMake]   Attempt to add link library "C:/Dev/3DxWare SDK/lib/x64/siapp.lib" to
1> [CMake]   target "CCAppCommon" which is not built in this directory.
1> [CMake] 
1> [CMake]   This is allowed only when policy CMP0079 is set to NEW.
```

**Comment by asmaloney** [comment]
OK - thank you. I'll have to try a workaround using a function like before.

In the meantime - this isn't related - I noticed this:

```
target_link_libraries( ${PROJECT_NAME} debug ${3DXWARE_LIB_DIR}/siapp.lib ${3DXWARE_LIB_DIR}/spwmathD.lib )
```

Is this supposed to link to a debug version of siapp.lib ? Does `siappD.lib`  exist in your installation?

**Comment by WargodHernandez** [comment]
> Is this supposed to link to a debug version of siapp.lib ? Does siappD.lib exist in your installation?
Here is the contents of the lib folder, so no it appears siapp didn't come with a debug library
image

**Comment by WargodHernandez** [comment]
I was able to generate, I'm building now, Ill let you know

**Comment by WargodHernandez** [comment]
it cant find 
image
from cc3DMouseManager.cpp

or 
image
from Mouse3DInput.cpp

**Comment by WargodHernandez** [comment]
should the `3DXWARE_INCLUDE_DIR` be added to
```
target_include_directories( ${PROJECT_NAME}
			PUBLIC
				${CMAKE_CURRENT_LIST_DIR}
		)
```

**Pull request merged**
