### PR TITLE
{cmake} Update LASFWFIO plugin

### PR DESCRIPTION
**Pull request by asmaloney**
I cannot build this plugin, and the CI doesn't either, so these changes require that someone try building it before merging.

### CODE REVIEW

**Comment by asmaloney** [comment]
:-) That's what I was waiting for.

What's the error?

**Comment by dgirardeau** [comment]
This plugins reuses the saveLASFileDlg.ui (and the corresponding .h and .cpp) from qPDALIO. But it can't find the ui file when uicing.

**Comment by dgirardeau** [comment]
It looks for it in the qLASFWFIO/src or qLASFWFIO/ui folders

**Comment by dgirardeau** [comment]
Oh, and I forgot:
```"${CMAKE_CURRENT_SOURCE_DIR}/../qPDALIO/include"```
--> there's no 'include' folder in qPDALIO, but a 'src' folder

**Comment by asmaloney** [comment]
There will be when the other PR is merged. https://github.com/CloudCompare/CloudCompare/pull/1196

**Comment by dgirardeau** [comment]
And what do you need to merge this PR?

**Comment by asmaloney** [comment]
Just hadn't got to it yet. I'm trying to keep these PRs "bite sized" so it's easier to find mistakes.

**Comment by dgirardeau** [comment]
Ok, it works now.

**Pull request merged**
