### PR TITLE
New features & some bugfixes

### PR DESCRIPTION
**Pull request by samthiele**
New features: 
 -XML and SVG exporters
 -single-surface geoobjects for structures such as faults, foliations

Bugfixes:
 -.csv export now writes american RHR (rather than british RHR).
 -geo-objects now a have a unique & persistent ID (these will be used by the topology tools).

### CODE REVIEW

**Comment by asmaloney** [comment]
Thanks Sam.

1) You've included "CloudCompare - Shortcut.lnk"
2) Would it be possible to break this into smaller PRs so it can be reviewed properly?

**Comment by samthiele** [comment]
Hi @asmaloney  - I've removed the shortcut that somehow slipped into my repo and fixed some small bugs that were stopping Travis from compiling.

And I'm not sure how to break the changes in this fork into multiple pull requests.

Cheers,
Sam

**Comment by dgirardeau** [comment]
As it's Sam's plugin, I trust him for properly managing its own plugin ;)

**Comment by asmaloney** [comment]
Sam:

For future changes, please make small PRs so they can be reviewed quickly/easily - one per "thing being solved".

When PRs are presented as "this does W, X, Y, and Z", then the reviewer is left with a large set of changes across many files and every change has to be picked apart by the reviewer - "is this part of W, X, Y, or Z?" - and the constant context switching makes it hard to focus on individual issues. This also makes discussion of the individual pieces more difficult.

Generally you want to focus on making small, orthogonal changes as opposed to one big one that does a bunch of things. I'd be happy to help with how to do that in the future.

Thank you for continuing to contribute!

**Pull request merged**
