### PR TITLE
Fix Loading files without normals

### PR DESCRIPTION
**Pull request by tmontaigu**

### CODE REVIEW

**Comment by dgirardeau** [comment]
Ah! I pushed my fix already. Can you rebase?

**Comment by tmontaigu** [comment]
It fixes the same bug but in a different way so I don't think its usefull to rebase + merge

**Comment by dgirardeau** [comment]
I like the // safeguard part though ;)

**Comment by dgirardeau** [comment]
Ah, I tried the online conflict solver of github, and it seems it didn't handled well spacings 😅

**Comment by dgirardeau** [comment]
Ok, the history was also weird with this merge commit... Should be fixed now.

**Comment by tmontaigu** [comment]
Yep its looks ok

**Pull request merged**
